# -*- coding: utf-8 -*-
"""DistribuiçãodadosamostraspH.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_aiuoLVtzw462H2uVDAF7Jl28DR8MW3A
"""

import pandas as pd 
read_file = pd.read_excel ("/content/drive/MyDrive/pHso.xlsx")

read_file.to_csv ("/content/drive/MyDrive/pHso.csv",  
                  index = None, 
                  header=True)

df = pd.DataFrame(pd.read_csv("/content/drive/MyDrive/pHso.csv"))

df

df['pH'].hist(bins=40)
plt.tight_layout()
plt.show()